theme: jekyll-theme-minimal

title: Armaan Singh
description: >-
  3rd year engineering student, interested in embedded systems, software,
  and cool side projects.
  <br><br>
  <strong>Quick links</strong><br>
  <a href="https://www.linkedin.com/in/PUT-YOUR-HANDLE">LinkedIn</a><br>
  <a href="/assets/Armaan_Singh_Resume.pdf">Download my resume</a><br>
  <a href="/assets/Armaan_Singh_Coop_Transcript.pdf">Download my co-op transcript</a>
